name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Build Solution
      run: |
        echo Display available configurations
        msbuild TouchFreeze.sln -pp | findstr "Release|Win32"
        echo Build the solution
        msbuild TouchFreeze.sln /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal
        echo Find msi file in powershell and output
        powershell -Command "Get-ChildItem -Path 'Executable\bin' -Filter '*.msi' -Name"
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Executable/bin/TouchFreeze.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
